USE [ACTIVACION]
GO
CREATE TABLE [dbo].[S_ACCESOS](
	[ID_ACCESO] [numeric](8, 0) IDENTITY(1,1) NOT NULL,
	[NOMBRE_ACCESO] [nvarchar](30) NOT NULL,
	[ORDEN] [numeric](2, 0) NOT NULL,
	[ACTIVO] [bit] NOT NULL,
	[FECHA_SERVIDOR] [datetime] NOT NULL,
	[FECHA_BAJA] [datetime] NULL,
 CONSTRAINT [PK_S_ACCCESOS] PRIMARY KEY CLUSTERED 
(
	[ID_ACCESO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[S_ACCESOS] ADD  CONSTRAINT [DF_S_ACCCESOS_ORDEN]  DEFAULT ((0)) FOR [ORDEN]
GO

ALTER TABLE [dbo].[S_ACCESOS] ADD  CONSTRAINT [DF_S_ACCCESOS_FECHA_SERVIDOR]  DEFAULT (getdate()) FOR [FECHA_SERVIDOR]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'TABLA DE ACCESOS  PARA APLICACIONES Y MODULOS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'S_ACCESOS'
GO