USE [ACTIVACION]
GO

CREATE TABLE [dbo].[S_PERFILES](
	[ID_PERFIL] [numeric](8, 0) IDENTITY(1,1) NOT NULL,
	[NOMBRE_PERFIL] [nvarchar](30) NOT NULL,
	[DESCRIPCION] [nvarchar](100) NULL,
	[ACTIVO] [bit] NOT NULL,
	[FECHA_ALTA] [datetime] NOT NULL,
	[FECHA_BAJA] [datetime] NULL,
	[FECHA_SERVIDOR] [datetime] NOT NULL,
	[ID_USUARIO_MODIFICA] [numeric](8, 0) NOT NULL,
 CONSTRAINT [PK_S_PERFILES] PRIMARY KEY CLUSTERED 
(
	[ID_PERFIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[S_PERFILES] ADD  CONSTRAINT [DF_S_PERFILES_FECHA_ALTA]  DEFAULT (getdate()) FOR [FECHA_ALTA]
GO

ALTER TABLE [dbo].[S_PERFILES] ADD  CONSTRAINT [DF_S_PERFILES_FECHA_SERVIDOR]  DEFAULT (getdate()) FOR [FECHA_SERVIDOR]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'TABLA DE PERFILES DE ACCESO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'S_PERFILES'
GO


