USE [ACTIVACION]
GO


CREATE TABLE [dbo].[S_USUARIOS](
	[ID_USUARIO] [numeric](8, 0) IDENTITY(1,1) NOT NULL,
	[ID_PERFIL] [numeric](8, 0) NULL,
	[USUARIO] [nvarchar](20) NOT NULL,
	[NOMBRE_USUARIO] [nvarchar](30) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[CORREO] [nvarchar](30) NULL,
	[ACTIVO] [bit] NOT NULL,
	[ULTIMA_SESION] [datetime] NULL,
	[FECHA_ALTA] [datetime] NOT NULL,
	[FECHA_BAJA] [datetime] NULL,
	[FECHA_SERVIDOR] [datetime] NOT NULL,
	[ID_USUARIO_MODIFICA] [numeric](8, 0) NULL,
	[ID_CLIENTE] [numeric](18, 0) NULL,
 CONSTRAINT [PK_S_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[S_USUARIOS] ADD  CONSTRAINT [DF_S_USUARIOS_FECHA_ALTA]  DEFAULT (getdate()) FOR [FECHA_ALTA]
GO

ALTER TABLE [dbo].[S_USUARIOS] ADD  CONSTRAINT [DF_S_USUARIOS_FECHA_SERVIDOR]  DEFAULT (getdate()) FOR [FECHA_SERVIDOR]
GO

ALTER TABLE [dbo].[S_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_S_USUARIOS_S_PERFILES] FOREIGN KEY([ID_PERFIL])
REFERENCES [dbo].[S_PERFILES] ([ID_PERFIL])
GO

ALTER TABLE [dbo].[S_USUARIOS] CHECK CONSTRAINT [FK_S_USUARIOS_S_PERFILES]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'TABLA DE USUARIOS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'S_USUARIOS'
GO


